### ISSUE TITLE
Module 12 Lab Change

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#10]
# Module: 12

Module 12's lab was updated to use Azure Automation DSC instead of Chef. It seems that Chef has moved from the server-client model to a new toolset called "Chef Automate". We were unable to figure out how to deliver this in a quality lab experience using the new pricing model.

If anyone has an idea how to re-incorporate Chef back into the labs, we are all ears 👍

**Comment by PoulJorgensen** [comment]
Thanks for the explanation.
I was wondering why the Lab didn't reflect what was written in the 20535A book.
