### ISSUE TITLE
Blocking Error at Mod 7, Ex 2, Task 2, step 8

### ISSUE THREAD

**Issue by Bethquinlan** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#12]
# Module: 07
#### Step: 8

App fails to load.  There's a note in the manual that states "If you click the browse button before the Web App has fully restarted, you may see an error message. Simply refresh your browser until the Web App is running again."  But the Swagger UI Home Page can't reach the server and never populates.  And I'm unsure if the error I'm seeing is the one referred to, or if I'm seeing a different error.  It might be good to add a statement to the manual as to what the expected error is.

![mod7-ex2-task2-step8-error](https://user-images.githubusercontent.com/17502756/35684438-b79747d0-071b-11e8-906e-1e09077065b5.png)

Performed lab twice with same results.  Initial research indicated that the problem could be related to CORS not being enabled, but CORS is enabled and set to * in the properties.

**Comment by edbakermct** [comment]
I ran this course twice last week and about 20% of students got this.

The remaining 805 all worked, there was NO difference in the lab.

I got this on the first course but on the second it ran fine.

Unsure how to diagnose this ‘transient’ error

Yours

Ed

**Comment by seesharprun** [comment]
@edbakermct: I see that you have been reading the developer architecture material 👍 

I am having a bit of a challenge reproducing this issue. What I will try next is to create an ARM template that deploys 10 versions of the Web App to see if I can use probability to create one that breaks.

**Comment by seesharprun** [comment]
I'm still having trouble reproducing the issue. I just want everyone to know that I am working on it now.

**Comment by JTomKinser** [comment]
I'm having the same problem.  I have recreated it 3 times and get the same error each time.  It's definitely reproducible for me.  It has not worked yet.  Please post any suggestions you may have.

**Comment by seesharprun** [comment]
We just ran through this lab again and was unable to reproduce the issue.

The error message indicates there's an issue with CORS but the web application is not making any cross-domain requests.

![image](https://user-images.githubusercontent.com/5067401/36273399-5baa8058-1252-11e8-89fc-709ce4693bc4.png)

**Comment by seesharprun** [comment]
Here's some of the external GitHub issues i'm reviewing to see if I can determine a cause:

- domaindrivendev/Swashbuckle.AspNetCore#593
- domaindrivendev/Swashbuckle.AspNetCore#325
- swagger-api/swagger-ui#146

**Comment by nugysemail** [comment]
Lab 7, Ex 2, Task 2, step 8

With Google Chrome Web Browser it worked.

With Microsoft Edge Web Browser it doesn't worked.
