### ISSUE TITLE
Mod 10, Ex. 2, Task 2, steps 2-3

### ISSUE THREAD

**Issue by Bethquinlan** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#20]
When I open a cloud shell and type the commands, this is what I see:

![20535a-mod10-ex2-task2-steps2_3-screenshot](https://user-images.githubusercontent.com/17502756/35822357-066f54c2-0a7a-11e8-88d0-5320fdc23428.JPG)

I am not familiar with Python, but what I'm seeing doesn't seem correct.  It appears as tho' I am not actually performing the commands and the requests library is not importing....

Is this correct?  If not, what should I do?

**Comment by seesharprun** [comment]
The Python interpreter will not provide feedback for the import statement. Would it help if this was a note after the lab instruction? From the screenshot, you did everything correct.

For the lines of code that follow after this, the Python interpreter will give a response of ``undefined``. This is acceptable as the expressions perform actions but do not return a result.

**Comment by nugysemail** [comment]
Lab 10, Ex. 2, Task 2, steps 3
showing error on Powershell but it worked on Bash
