### ISSUE TITLE
hot to build the word documents ?

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#21]
Hello how to build the AK files word docs 
tks
no pando

**Comment by seesharprun** [comment]
The Word documents are automatically built and available here:

https://github.com/MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions/releases

If you want instructions on how to manually build the files, I would be happy to post them. It involves Docker so I assumed most MCTs would be uninterested
