### ISSUE TITLE
Invalid link to Lab 07 on microsoftlearning.github.io

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#22]
# Module: 07
#### Step: 00

Description of issue
The link on microsoftlearning.github.io to lab 7 doesn't work. It points to a file in Mod06

Repro steps:

1. https://microsoftlearning.github.io/20535-ArchitectingMicrosoftAzureSolutions/
1. Select module 7
1. https://microsoftlearning.github.io/20535-ArchitectingMicrosoftAzureSolutions/Instructions/Labs/**Mod06/**20535A_LAB_AK_07.md doesn't exist

**Comment by seesharprun** [comment]
This issue should be resolved now by pull request #23
