### ISSUE TITLE
Portal Update - Create a Resource and All Services

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#28]
# Module: All
#### Step: All

Description of issue
Portal Hub is updated. **+New** and **More Services** are replaced by **+Create a Resourse** and **All Services**.

Repro steps:

1. https://portal.azure.com
1.
1.

**Comment by seesharprun** [comment]
@tiagocostapt just fixed all of these links.

You should see the updated instructions here: https://github.com/MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions/releases/tag/A-v1.1.0
