### ISSUE TITLE
I can not see the results of the query. #MOD7

### ISSUE THREAD

**Issue by kimsejun2000** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#37]
# Module: 07
#### Step: 11~15

Description of issue
I clicked the Try it out! button as follows.
![image](https://user-images.githubusercontent.com/15935463/36718525-7855b618-1be5-11e8-9645-47b6c8af3fa4.png)

The results is "[]" in Response Body. I checked the Azure search to created "Exercise 3". It is "Failed" in "Indexer".
![image](https://user-images.githubusercontent.com/15935463/36718808-67f618c0-1be6-11e8-9f38-b500007a73e2.png)

Error message is:
[
    {
        "key": "5943bc40-aa0b-848c-e38e-782e94d416ea",
        "errorMessage": "Input string was not in a correct format. Couldn't store <90000.00> in salary column.  Expected type is Int64."
    }
]

As I guess, when I execute the Post command in Step 13 of Task 02 of Lab 02, the data seems to be input as Text. Is it normal? or did I do something wrong?

You can see the data of my CosmosDB as follows.
https://apiptzrvc5yijqos.azurewebsites.net/#/
https://apiptzrvc5yijqos.azurewebsites.net/Documents

Best regards,
Sejun.

**Comment by seesharprun** [comment]
This is very strange. Looking at your sample, the Stored Procedure in Cosmos put in strings instead of numeric values.

The source code for the sproc is here: https://github.com/azure-labs/cosmos-api/blob/master/Cosmos.API/Scripts/genDocuments.js.

I am working on reproducing this issue.

**Comment by seesharprun** [comment]
I just updated the script to convert back from strings to numbers.

azure-labs/cosmos-api@9d7d405

Try running the lab again and please report back if you see another issue

**Comment by kimsejun2000** [comment]
Great! I check it and it is normal.
