### ISSUE TITLE
Request word correction #MOD 8

### ISSUE THREAD

**Issue by kimsejun2000** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#38]
# Module: 08
#### Step: 23, 29, .\Allfiles\Mod08\Labfiles\Starter\copy.json

Description of issue
23.
"properties": {           
    "availabilitySet": {
        "id": "[resourceId('Microsoft.Compute/availabilitySets',variables('availabilitySetName'))]"
    }, 
...
=>
"properties": {           
    "availabilitySet": {
        **"id": "[resourceId('Microsoft.Compute/availabilitySets', 'BalancedSet')]"**
    }, 
...

29.
{
    "type": "Microsoft.Compute/availabilitySets",
    "name": "BalancedSet",
    "apiVersion": "2017-12-01",
    "location": "[resourceGroup().location]",
    "sku": {
        "name": "Classic"
    },
    "properties": {
        "platformFaultDomainCount": "2",
        "platformUpdateDomainCount": "2"
    }
}
=>
{
    "type": "Microsoft.Compute/availabilitySets",
    "name": "BalancedSet",
    "apiVersion": "2017-12-01",
    "location": "[resourceGroup().location]",
    "sku": {
        **"name": "Aligned"**
    },
    "properties": {
        "platformFaultDomainCount": "2",
        "platformUpdateDomainCount": "2"
    }
}

.\Allfiles\Mod08\Labfiles\Starter\copy.json (Deployment failed)
...
        {
            "type": "Microsoft.Compute/availabilitySets",
            "name": "BalancedSet",
            "apiVersion": "2017-12-01",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "Aligned"
            },
            "properties": {
                "platformFaultDomainCount": 2,
                "platformUpdateDomainCount": 2
            }
        },
...
=>
...
        {
            "type": "Microsoft.Compute/availabilitySets",
            "name": "BalancedSet",
            "apiVersion": "2017-12-01",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "Aligned"
            },
            "properties": {
                "platformFaultDomainCount": "2",
                "platformUpdateDomainCount": "2"
            }
        },
...

Check please

Best regards,
Sejun.

**Comment by seesharprun** [comment]
I am not sure what you are asking here. I was able to parse two requests:

1. Change the availability set's id to reference a hard-coded constant instead of a variable
1. Change the SKU from Classic to Aligned

Can you verify?

**Comment by kimsejun2000** [comment]
Okay! That's right.
It is pointed out that the contents are different from each other.

1. The contents of Step 23 and Step 24 are different.
![image](https://user-images.githubusercontent.com/15935463/36775664-534f3b3e-1ca6-11e8-8609-cb08f14f3249.png)
![image](https://user-images.githubusercontent.com/15935463/36775676-5e8ce230-1ca6-11e8-9ccd-aa7d4be38746.png)

2. This ARM template deploys VMs that support Managed Disks. So, the SKU in Step 29 is **Aligned**.
