### ISSUE TITLE
Module 5 lab

### ISSUE THREAD

**Issue by richard-oertle** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#39]
# Module: 05
#### Step: 03

Description of issue In the first exercise, task 3 in step 3 it asks you to determine if .net 4.7 is loaded, and if you type the command as written (  az webapp list-runtimes ), it will show the runtime is available. This is because the default is windows, and it shows the 4.7 runtime is loaded. However since you are completing the task in Linux, you need to add a --LINUX at the  end of the command (  	az webapp list-runtimes --Linux) and it will show that it is NOT loaded, and that is why the task fails.
****
Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
I am on site at the Microsoft MVP summit so I won’t be able to fix the repo until sometime next week.

Is this blocking you or a student from completing the lab?

**Comment by richard-oertle** [comment]
Wow, been teaching MS courses for 19 years and NEVER had a course author respond so well or so fast! THANK YOU.


No problem, what we did was to add the --Linux parameter, as I listed, look to see what runtimes were loaded and substitute that using .netcoreXX in place of .net 4.7 and everything worked fine. Just wanted you and the other instructors know about the problem. Just trying to contribute.


Richard


________________________________

**Comment by richard-oertle** [comment]
Another fix I would prefer to just send to you directly:


In module 8 lab exercise from Github, exercise 2 task 1, step 29 has you set the Platformfaultdomaincount to 2. In the lab steps it shows it in double quotes, declaring it to be a string, and it does not work. Taking out the double quotes makes it an integer and it does work. Same for platformupdatedomaincount. If you go to the actual file on drive F of the virtual machine, it is correct. so if the student cuts and pastes from the lab manual steps it fails, but if from the scripts i=on the VM it works.


Richard


________________________________

**Comment by seesharprun** [comment]
I set aside some time on Wednesday to tackle this issue. I will create a Pull Request to resolve both and give you an opportunity to review the pull request to make sure the resolution works for you.

Does that work?

**Comment by richard-oertle** [comment]
Sydney, I am so happy that we have a github location to coordinate lab updates and the ability to work with the author, that anything you do is great with me.


Thanks for working with us front line MCTs


Richard


________________________________

**Comment by seesharprun** [comment]
There's an open PR to address your first issue now. When you get a chance, please review it to see if it solves your original issue.

The second issue will be addressed in a separate PR.

**Comment by seesharprun** [comment]
I was checking in to see if you had a chance to review the fixes.

**Comment by nugysemail** [comment]
Module 5
Exercise 1 Task 3 Step 3
az webapp list-runtimes --linux

Result :
[
  "RUBY|2.3",
  "NODE|4.4",
  "NODE|4.5",
  "NODE|4.8",
  "NODE|6.2",
  "NODE|6.6",
  "NODE|6.9",
  "NODE|6.10",
  "NODE|6.11",
  "NODE|8.0",
  "NODE|8.1",
  "NODE|8.2",
  "NODE|8.8",
  "NODE|8.9",
  "NODE|9.4",
  "PHP|5.6",
  "PHP|7.0",
  "PHP|7.2",
  "DOTNETCORE|1.0",
  "DOTNETCORE|1.1",
  "DOTNETCORE|2.0",
  "TOMCAT|8.5-jre8",
  "TOMCAT|9.0-jre8",
  "GO|1"
]

Exercise 1 Task 3 Step 4
az --% webapp create --name blankinterestingapp --plan HostedServicePlan --resource-group MOD05APPS --runtime "DOTNETCORE|2.0"

Result :

{
  "additionalProperties": {},
  "availabilityState": "Normal",
  "clientAffinityEnabled": true,
  "clientCertEnabled": false,
  "cloningInfo": null,
  "containerSize": 0,
  "dailyMemoryTimeQuota": 0,
  "defaultHostName": "blankinterestingapp.azurewebsites.net",
  "enabled": true,
  "enabledHostNames": [
    "blankinterestingapp.azurewebsites.net",
    "blankinterestingapp.scm.azurewebsites.net"
  ],
  "ftpPublishingUrl": "ftp://xxxx-xxxx-xxx-xxx.ftp.azurewebsites.windows.net/site/wwwroot",
  "hostNameSslStates": [
    {
      "additionalProperties": {
        "ipBasedSslResult": null,
        "ipBasedSslState": "NotConfigured",
        "toUpdateIpBasedSsl": null
      },
      "hostType": "Standard",
      "name": "blankinterestingapp.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "virtualIp": null
    },
    {
      "additionalProperties": {
        "ipBasedSslResult": null,
        "ipBasedSslState": "NotConfigured",
        "toUpdateIpBasedSsl": null
      },
      "hostType": "Repository",
      "name": "blankinterestingapp.scm.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "virtualIp": null
    }
  ],
  "hostNames": [
    "blankinterestingapp.azurewebsites.net"
  ],
  "hostNamesDisabled": false,
  "hostingEnvironmentProfile": null,
  "httpsOnly": false,
  "id":"/subscriptions/XXXXXXXX
XXXXXXXXX/resourceGroups/MOD05APPS/providers/Microsoft.Web/sites/blankinterestingapp",
  "identity": null,
  "isDefaultContainer": null,
  "kind": "app,linux",
  "lastModifiedTimeUtc": "2018-04-21T05:13:17.886666",
  "location": "East US",
  "maxNumberOfWorkers": null,
  "name": "blankinterestingapp",
  "outboundIpAddresses": "xx.xx.xxx.xx,xx.xx.x.xxx,xx.xxx.xxx.xx,xx.xx.x.xx,xx.xxx.xxx.xxx",
  "possibleOutboundIpAddresses": "xx.xx.xx.xx,xx.xx.x.xxx,xx.xxx.xxx.xx,xx.xx.x.xx,xx.xxx.xxx.xxx,xx.xx.xxx.xx",
  "repositorySiteName": "blankinterestingapp",
  "reserved": true,
  "resourceGroup": "MOD05APPS",
  "scmSiteAlsoStopped": false,
  "serverFarmId":"/subscriptions/xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx/resourceGroups/MOD05APPS/providers/Microsoft.Web/serverfarms/HostedServicePlan",
  "siteConfig": null,
  "slotSwapStatus": null,
  "snapshotInfo": null,
  "state": "Running",
  "suspendedTill": null,
  "tags": null,
  "targetSwapSlot": null,
  "trafficManagerHostNames": null,
  "type": "Microsoft.Web/sites",
  "usageState": "Normal"
}

**Comment by nugysemail** [comment]
Lab 5
Exercise 2 Task 1 Step 2
az --% webapp create --name githubproject --plan HostedServicePlan --resource-group MOD05APPS --runtime "node|8.1"
