### ISSUE TITLE
Lab03/Task02: User has to select at least one setting from the  "Select public inbound ports" dropdown

### ISSUE THREAD

**Issue by PowershellNinja** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#48]
# Module: 03
#### Step: 07

Description of issue
In the current interface, users cannot just accept all the default values as the "Select public inbound ports" setting requires the user to select at least one setting.

Repro steps:

1. Follow the steps of th lab, tasks 1 and 2
2. Follow all vm configuration steps until after the size selection
3. Click on te OK button in the settings blade without changing any settings
4. The portal does not let you proceed as you have to at least choose one setting from the  "Select public inbound ports" Dropdown.

**Comment by tiagocostapt** [comment]
Yes, the UI have changed in the last days. We need to readjusted the lab steps.

**Comment by tiagocostapt** [comment]
Thanks for reaching. The Lab Instructions are now changed.
