### ISSUE TITLE
Missing/Incorrect Steps in MOd 08, Ex 1, Task 3

### ISSUE THREAD

**Issue by jfinleynz** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#53]
# Module: 08
#### Step: 2/3

Description of issue
It would appear that either a step is missing or the description of the az command is wrong. It indicates that you will be running a command to list the resource groups. The command in the step is to install the vm extensions.

I suspect that either you want users to list the resource groups and then install the extension (in which case you're missing a step) or you need to rewrite step 2 to reflect what the code does.

**Comment by tiagocostapt** [comment]
Fixed. Thanks for reaching out.
