### ISSUE TITLE
Default Pricing Tier Service Bus

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#55]
# Module: 11
#### Step: 00

Description of issue
Instruction says leave the default pricing tear option, however there is no pricing tier selected. You can choose between basic, standard and premium. Should the option be basic or is standaard needed?

Repro steps:

1. Create Service Bus
2. Enter namespace
3. Select pricing tier

This is also relevant for the 20532 and the 20776 courses.

![image](https://user-images.githubusercontent.com/10166617/42995850-3003f198-8c12-11e8-94e1-2515dd7bb435.png)

**Comment by seesharprun** [comment]
We will need to test this but I believe Standard was the original default option. Can you add an issue to the other courses too so we can track this?
