### ISSUE TITLE
Lab 03 - Creation of VM

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#73]
![image](https://user-images.githubusercontent.com/23341813/48395957-2bcf3a80-e719-11e8-8596-fff290159658.png)

The instructions need updating to explain what setting needs selecting for inbound ports. (this is from the v1.3 release)

ALSO no indication of what vm image to use....

**Comment by seesharprun** [comment]
@tiagocostapt, can you look at this?

**Comment by tiagocostapt** [comment]
@seesharprun Yes. Tomorrow I will have a look at it.

**Comment by tiagocostapt** [comment]
@edbakermct and @seesharprun  all done.
