### ISSUE TITLE
Module 12 - wrong linux.json inside the VMs

### ISSUE THREAD

**Issue by cblackuk** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#85]
# Module: 12
### Task: 03

Description of issue

Wrong linux.json is on the actual VMs - GitHub repo is ok.

My fix:
Virtual Machines have Suse linux.json so you cannot complete the last task.

I produced a quick bash script to fix it.

Links:
https://fixossa.blob.core.windows.net/fixos/fixos.sh
https://fixossa.blob.core.windows.net/fixos/readme.md

Readme:
# How to use it - from your Lab VM

1.  Open Bash for Windows
2.  Change directory to F: drive:

    ```shell
    cd /mnt/f
    ```

3.  Download it via **wget**:

    ```shell
    wget https://fixossa.blob.core.windows.net/fixos/fixos.sh
    ```

4.  Execute the script:

    ```shell
    ./fixos.sh
    ```

## Actual Script for reference:

```bash
#!/bin/bash
filepath="/mnt/f/Mod12/Labfiles/Starter/linux.json"
oscheck=$(grep -i '"suse"' $filepath)

echo "OS is $oscheck"
echo "Your file path is: $filepath"
if [ "$oscheck" ]; then
    echo "True"
    echo "OS is $oscheck so we will need to change it to CentOS"
    echo "Changing $filepath file..."
    sed -i 's/"suse"/"OpenLogic"/g' $filepath &&
    sed -i 's/"opensuse-leap"/"CentOS"/g' $filepath &&
    sed -i 's/"42.3"/"7.5"/g' $filepath
else
    echo "False"
    echo "OS is not Suse - no need to change it to CentOS"
fi
```

> **Note** The links will expire soon but you can still use the code if you need to.

**Comment by tiagocostapt** [comment]
@cblackuk when you refer to "actual VMs" are you referring for the 20535 VMs? You always should update the allfiles with the files from GitHub.

**Comment by cblackuk** [comment]
@tiagocostapt I am referring to VirSoft.Net VMs provided for GK training that has got outdated json file as they have only pulled the repo once and never updated it. I wrote it so that my class can actually complete the lab successfully.

This can be closed after today if nobody else is bothered :-)

**Comment by tiagocostapt** [comment]
@cblackuk ok. I will inform Virsoft about that. I will close this issue later today.

**Comment by edbakermct** [comment]
Or use labs that update regularly 😓

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security

________________________________

**Comment by cblackuk** [comment]
Thanks @tiagocostapt! Would be nice if you could also merge my PRs though...

**Comment by tiagocostapt** [comment]
@seesharprun can we merge @cblackuk PRs?

**Comment by seesharprun** [comment]
They keep coming in. I am waiting for the last PR for this week to land before I do another release.
